### ISSUE TITLE
Feature proposal : Docker container

### ISSUE THREAD

**Issue by jaymoulin** [kryptxy/torrench#36]
To ease installation and dependencies, propose some docker images so one can automatize some processes or a give full operational isolated system

**Comment by kryptxy** [comment]
Okay this is something new (Docker noobie here!). I have never worked with docker (Though I have heard a little) - How would it be beneficial or what's the advantage of using this?

**Comment by jaymoulin** [comment]
This would be beneficial because it saves the current state of the project and all its dependencies. It's really easy to install as a user (not programmer) don't need to know what dependencies to install, if it stills exists or not, variables to set etc...

Right now, torrench needs to have gcc, libxml, python >= 3 etc to work... with docker installed :

```
docker run -ti torrench --version
````

is the only command needed to display current version.

as I already compile the current docker image, you can test it with docker installed on pc with this command :

```
docker run --rm -ti jaymoulin/rpi-torrench:pc --version
```

**Comment by datafanatic** [comment]
What advantage would this have instead of the current `pip(3) install torrench` approach? Also, `gcc` is a Python dependency, no? I'm also not savvy with Docker, so please excuse my ignorance.

**Comment by jaymoulin** [comment]
Assume one or more dependency of torrench is deleted from pip (which can occurs if the one maintainer decide to deleted it from pip, (which occured on NPM if you followed NodeJS news)), or a dependency need another dependency, which need something else to be installed or configured : torrench or `pip install torrench` won't work in that case.
Also, you MUST know what extension has to be installed when you type your `pip install` command and add what you need each time it fails ans interpret every error.

With Docker, already has already been compiled so you won't have any of this problem whatever happens.

Also it gives you one more way to install torrench. But, even if you refuse this PR, I already have compiled it so I'll maintain this as long as I can, whatever you choose.

**Comment by datafanatic** [comment]
Oh, I see. That's pretty interesting. So it works kind of like a small VM whose sole purpose is to run configure, build and run torrench? Also, regarding the PR, I'm not responsible for that as I'm just a contributor, much like yourself. I was just curious regarding the advantages of Docker since it seems to be used quite a lot nowadays but I never really had the time (or patience, really) to study about it.

**Comment by jaymoulin** [comment]
It's not VM but you can use this paradigm to understand the point

**Comment by kryptxy** [comment]
This looks interesting. 
@jaymoulin I am gonna try it today. Still got a few questions which I hope will be answered once I get my hands dirty with docker.

About PR - I seriously doubt I won't accept it. This is really interesting and something different (Thank you!). Just I'd like to try it myself and see how things work with docker.

**Comment by kryptxy** [comment]
Hi,
I played with docker a bit (It's awesome btw). I faced a few issues:
* After downloading torrench docker image, command ```docker run --rm -ti jaymoulin/rpi-torrench torrench --help``` gives error ```standard_init_linux.go:187: exec user process caused "exec format error"```. I tried finding a fix, but the issue mentioned everywhere (about missing ```#!/bin/sh```) is not the issue here. Did I miss something?
    * I tried the ```hello-world``` and ```ubuntu``` images. They worked fine.

* I further tried building the docker image(named ```test```), and it built successfully. Command ```docker run -it test torrench -h``` runs successfully. 
However, torrench requires a config file to enable TPB/KAT... searches (config file's location is ```$HOME/.config/torrench```). How can this be resolved?

**Comment by jaymoulin** [comment]
You found out for yourself for the first problem before I could explain you.

For the second problem, you have to mount a volume for your container to access your host files :

For example:
```
docker run --rm -ti -v $HOME/.config/torrench:/root/.config/torrench jaymoulin/rpi-torrench:pc -t <foo>
```

**Comment by kryptxy** [comment]
It worked. Thanks.

Can this be made stand-alone? I mean instead of mounting host's ```$HOME/.config/torrench``` to container, a script that could directly download the config.ini file to container? (If I am not wrong, a few modifications to ```Dockerfile``` should help achieve this?). If not a script, then maybe user could download the config file to host, and then  copy the config file to container? (```docker cp``` I suppose).
This would eliminate torrench's dependency on host for config file, and will make torrench-docker a stand-alone.

**Comment by jaymoulin** [comment]
No problem, just give me the config files I need to add and where and I'll handle that

**Comment by kryptxy** [comment]
Hey, by adding wget command I meant the wget command would be executed _after_ docker image is downloaded. The config file should not be downloaded along with docker image. The docker image by default should not contain the ```config.ini```. 

After downloading docker image - command ```docker run -it jaymoulin/rpi-torrench:pc  mkdir -p /root/.config/torrench && wget -O /root/.config/torrench/config.ini https://pastebin.com/raw/reymRHSL``` could be used to download the config file. 

I tried this command but got ```Permission denied``` message. And for ```wget``` to run, ```openssl``` dependency was required (appending ```openssl``` [here](https://github.com/jaymoulin/torrench/commit/3d842819396f1aa347f94b32ae81ac966d4dd086#diff-a7129f00b8af20b97ebaa2f46a961fc2R7) did the trick).

**Comment by jaymoulin** [comment]
I don't understand why you need this file to be downloaded later? Also you can install all those dependencies manually instead of adding it in the docker image

**Comment by kryptxy** [comment]
> I don't understand why you need this file to be downloaded later?

This is how torrench functions. To enable TPB/KAT... sites, the config file needs to be downloaded separately by user, and needs to be enabled as well. We can't provide the ```config.ini``` file along with image. TPB/KAT sites are disabled by default.

> Also you can install all those dependencies manually instead of adding it in the docker image 

That would be fine too.

---

This is what I have in mind:
* User downloads the docker image
    * By default TPB/KAT... sites are disabled. However linuxtracker and Distrowatch are fully functional since they do not depend on ```config.ini``` file.
* To enable TPB/KAT sites, the user should download and enable the ```config.ini``` file. 
    * These steps would be mentioned in documentation, along with legal warnings (like [here](https://github.com/kryptxy/torrench#-using-tpbkatskytnyaaxbit))

**Comment by jaymoulin** [comment]
I get that the option has to be activated by the user to enable the feature but I don't get why he has to **DOWNLOAD** that file separately. 

If I provide the file with the image I can still be able to force the user activate something for him to use this functionality.

Even if the file must be maintained with your new releases, It will not be compatible with late revisions so we'll lose the purpose of Docker

**Comment by kryptxy** [comment]
I see. Okay. So include the file with image, but set ```enable=0```. And let user enable the file.

**Comment by datafanatic** [comment]
I think all of this could be solved with a simple check to see if the user is running torrench for the first time, then ask the user to enable the modules.
For example:

`$ torrench -t "ghost in the shell"`
`This seems to be the first time that you are running torrench. Some modules may contain illegal content so we ask that you enable them manually. Would you like to enable them? [y/n]`

If `y`, the configuration file will be created by torrench itself with all the modules enabled. Otherwise, only the default modules would be enabled. 

To check whether the user is running torrench for the first time we could simple create a `.torrench` file in the current directory. If this file exists, then proceed according to the configuration, if it doesn't, print the above message and proceed. I think this would be more practical, specially concerning updates and new modules.

**Comment by jaymoulin** [comment]
usage example with this new PR
Without illegal sites
```
docker run --rm -ti jaymoulin/rpi-torrench:pc torrench debian
```
With illegal sites
```
docker run --rm -ti jaymoulin/rpi-torrench:pc --risky debian
```

**Comment by kryptxy** [comment]
Looks great. Two (final) changes:

1. Every time I run search command with ```--risky``` argument, the entire ```config.ini``` file is displayed in console, followed by search. Can this config file be removed from display? Silently enabling the file would be great.

2. It would be better to enable the config file once. (That is not to pass ```--risky``` argument every time to search TPB/KAT/etc). Also a prompt Confirming the same would be great (as suggested by @datafanatic). 
Prompt message: ```Confirm enabling config.ini file? Some modules may contain illegal content so we ask that you enable them manually. Would you like to enable them [y/n]: ```

Can these be done?

**Comment by jaymoulin** [comment]
> Every time I run search command with --risky argument, the entire config.ini file is displayed in console, followed by search. Can this config file be removed from display? Silently enabling the file would be great.

I compiled with debug on. I fixed it. Nothing changed in PR

> It would be better to enable the config file once. (That is not to pass --risky argument every time to search TPB/KAT/etc). Also a prompt Confirming the same would be great (as suggested by @datafanatic).
> Prompt message: Confirm enabling config.ini file? Some modules may contain illegal content so we ask that you enable them manually. Would you like to enable them [y/n]:
> 

I can't keep state. You can bypass this with this command :

```
wget "https://pastebin.com/raw/reymRHSL" -O $HOME/torrench.ini && sed -i "s/enable = 0/enable = 1/g" $HOME/torrench.ini && docker run --rm -ti -v $HOME/torrench.ini:/root/.config/torrench/config/ini jaymoulin/rpi-torrench:pc torrench "illegal_activated_string"
```

**Comment by RafayGhafoor** [comment]
> It would be better to enable the config file once. (That is not to pass --risky argument every time to search TPB/KAT/etc). Also a prompt Confirming the same would be great (as suggested by @datafanatic).
Prompt message: Confirm enabling config.ini file? Some modules may contain illegal content so we ask that you enable them manually. Would you like to enable them [y/n]:

Implemented at https://github.com/kryptxy/torrench/pull/42

**Comment by kryptxy** [comment]
@jaymoulin Thanks for your work. Really appreciated. I find docker amazing, and can see why devs love it. Still got to explore it and learn more about it :) Thanks for bringing it in.
Merging PR! Cheers!
