### ISSUE TITLE
Make Index Number Visible

### ISSUE THREAD

**Issue by z1lt0id** [kryptxy/torrench#48]
Just wondering if there is an option to enable the index number of each torrent? It's annoying trying to count all the way down the list ;)

**Comment by kryptxy** [comment]
What do you mean? Each torrent has an associated index.

**Comment by prakashdanish** [comment]
@z1lt0id the second collumn literally does that.

@kryptxy Off-topic: Just saw cli-amizone, was wondering how you'll authenticate? using selenium because that's what I did [here](https://github.com/prakashdanish/amizone-cli) and if not, then do let me know, I'm curious as to learning other ways of doing just that.

**Comment by kryptxy** [comment]
@prakashdanish Nice! Looks great. 

I used the ```requests``` module (```requests.session```). See [Authenticate.py](https://github.com/kryptxy/cli-amizone/blob/master/amizone/Authenticate.py) file. 
You may ping me [Twitter/Telegram](https://github.com/kryptxy/torrench#contact) or [create an issue](https://github.com/kryptxy/cli-amizone/issues/new) and we can discuss this further if you'd like to :)

Cheers!
